### ISSUE TITLE
Infrastructure Cost Audit

### ISSUE THREAD

**Issue by kespinola** [holaplex/kubes#15]
## Goal
Understand and track infrastructure costs for AWS and Heroku.

## AWS Tasks
- [x] Catalogue infrastructure by service, environment, and cost center using tags
- [x] Generate cost reports in cost management based above tagging scheme
- [x] Give @kespinola access to cost management
- [x] Construct recommend [savings plan](https://us-east-1.console.aws.amazon.com/cost-management/home?region=us-east-1#/savings-plans/overview) for compute

## Heroku Tasks
- [x] Audit  [Sept Invoice](https://particleboard.heroku.com/teams/holaplex/invoices/72823739) to determine which services can be decommissioned or migrated to AWS

**Comment by mpwsh** [comment]
### Regarding cost management on Heroku:

RabbitMQ is still hosted there as an add-on (1000 USD/month for Prod MQ + 500 USD for Stage MQ).   

We’ve been holding the migration to relief some ‘maintenance burden’ because we didn’t know how difficult it was to maintain a self hosted rabbit instance.

After testing  RabbitMQ on the devnet Kubernetes cluster alongside the devnet validator i can confidently say we can move that to kubernetes as well (using the RabbitMQ operator to manage balancing and scaling)

Sept Invoice was 2k tho, so need to kill whatever is generating those extra 500 USD.

### Most importantly:
This will enable us to use the same reserved instance plan we can get for our kubernetes nodes `m5.2xlarge` (8cpu 32GB ram) — which is around 40% discount if we pay 1-year-upfront (its around 17k for the full 1-year upfront, but then our Kube nodes will cost $0 -- Which means everything we can get into kubes will cost us $0 for the next year (excluding added Persistent storage)

### Regarding cost management on AWS:
I [created a spreadsheet](https://docs.google.com/spreadsheets/d/1yNYSJPORIxa1pZCa0Nat2jtH9zDnPO6efStsTIRtoLU/edit#gid=0) with our AWS indexer stack cost, showing potential discounts we can get on paying reserved instances (partial upfront vs full upfront vs on-demand).  
**Note:** I'm setting the kube nodes to 8 although we are running only 4 at the moment, because i think we can also run scyllaDB and rabbitMQ in kubes too, and those nodes will be reserved to just run that (and no other workload).

**Comment by mpwsh** [comment]
Created [notion doc ](https://www.notion.so/holaplex/Cost-audit-Sept-2022-3917e11a0dc14a36b271cfdea25b7b7d) with details about sept infra cost, including optiosn for reserved instances

**Comment by kespinola** [comment]
- Every log line is generating traffic cross AZ
- Devnet is generating large NAT traffic to fake URLs:
  - Rate limiting on the assets service
  - Use api token & allows on domains for assets service with CORs
  - Track invalid asset URLs in the http consume so we don't continue to reach out for bad assets

**Comment by kespinola** [comment]
- Tune logging

**Comment by kespinola** [comment]
https://github.com/holaplex/kubes/issues/19

Cataloging moved to its own issue to be completed in the future.
